var Name = [
    "the sad onion",
    "the inner eye",
    "spoon bender",
    "cricket's head",
    "my reflection",
     "number one",
    "blood of the martyr",
    "brother baby",
    "skatole",
    "halo of flies",
    "1UP",
    "Magic Mushroom",
    "The Virus",
    "Roid Rage",
    "<3",
    "Raw Liver",
    "Skeleton Key",
    "A Dollar",
    "Boom!",
    "Transcendance",
    "The Compass",
    "Lunch",
    "Dinner",
    "Dessert",
    "Breakfast",
    "Rotten Meat",
    "Wooden Spoon",
    "The Belt",
    "Mom's Underwear",
    "Mom's Heels",
    "Mom's Lipstick",
    "Wire Coat Hanger",
    "The Bible",
    "The Book of Belial",
    "The Necronomicon",
    "The Poop",
    "Mr. Boom",
    "Tammy's Head",
    "Mom's bra",
    "Kamikaze!",
    "Mom's Pad",
    "Bob's Rotten Head",
    "Teleport!",
    "Yum Heart",
    "Lucky Foot",
    "Doctor's Remote",
    "Cupid's Arrow",
    "Shoop Da Whoop",
    "Steven",
    "Pentagram",
    "Dr.Fetus",
    "Magneto",
    "Treasure Map",
    "Mom's Eye",
    "Lemon Mishap",
    "Distant Admiration",
    "Book of Shadows",
    "The Ladder",
    "Charm of the Vampire",
    "The Battery",
    "Steam Sale",
    "Anarchist Cookbook",
    "The Hourglass",
    "Sister Maggy",
    "Technology",
    "Chocolate Milk",
    "Growth Hormones",
    "Mini Mush",
    "The Rosary",
    "Cube of Meat",
    "A Quarter",
    "PHD",
    "X-Ray Vision",
    "My Little Unicorn",
    "Book of Revelation",
    "The Mark",
    "The Pact",
    "Dead Cat",
    "Lord of the Pit",
    "The Nail",
    "We Need to go Deeper",
    "Deck of Cards",
    "Monstro's Tooth",
    "Loki's Horns",
    "Little Chubby",
    "Spider Bite",
    "The Small Rock",
    "Spelunker Hat",
    "Super Bandage",
    "The Gamekid",
    "Sack of Pennies",
    "Robo-Baby",
    "Little C.H.A.D",
    "The Book of Sin",
    "The Relic",
    "Little Gish",
    "Little Steven",
    "The Halo",
    "Mom's Bottle Of Pills",
    "The Common Cold",
    "The Parasite",
    "The D6",
    "Mr.Mega",
    "The Pinking Shears",
    "The Wafer",
    "Money = Power",
    "Mom's Contact",
    "The Bean",
    "Guardian Angel",
    "Demon Baby",
    "Mom's Knife",
    "Ouija Board",
    "9 Volt",
    "Dead Bird",
    "Brimstone",
    "Blood Bag",
    "Odd Mushroom",
    "Odd Mushroom",
    "Whore of Babylon",
    "Monster manual",
    "Dead Sea Scroll",
    "Bobby Bombs",
    "Razor Blade",
    "Forget Me Now",
    "Forever Alone",
    "Bucket of Lard",
    "The Pony",
    "Bomb Bag",
    "A Lump of Coal",
    "Guppy's Paw",
    "Guppy's Tail",
    "IV Bag",
    "Best Friend",
    "Remote Detonator",
    "Stigmata",
    "Mom's Purse",
    "Bob's Curse",
    "Pageant Boy",
    "Scapular",
    "Speed Ball",
    "Bum Friend",
    "Guppy's Head",
    "The Prayer Card",
    "Notched Axe",
    "Infestation",
    "IPECAC",
    "Tough Love",
    "The Mulligan",
    "Technology 2",
    "Mutant Spider",
    "Chemical Peel",
    "The Peeper",
    "The Habit",
    "Bloody Lust",
    "Crystal Ball",
    "Spirit of the Night",
    "Crack the Sky",
    "Ankh",
    "Celtic Cross",
    "Ghost Baby",
    "The Candle",
    "Cat-o-nine Tails",
    "D20",
    "Harlequin Baby",
    "Epic Fetus",
    "Polyphemus",
    "Daddy Longlegs",
    "Spider Butt",
    "Sacrificial Dagger",
    "Mitre",
    "Rainbow Baby",
    "Dad's Key",
    "Stem Cells",
    "Portable Slot",
    "Holy Water",
    "Fate",
    "The Black Bean",
    "White Pony",
    "Sacred Heart",
    "Toothpicks",
    "Holy Grail",
    "Dead Dove",
    "Blood Rights",
    "Guppy's Hairball",
    "Abel",
    "SMB Super Fan",
    "Pyro",
    "3 Dollar Bill",
    "Telepathy for Dummies",
    "Meat!",
    "Magic 8 Ball",
    "Mom's Coin Purse",
    "Squeezy",
    "Jesus Juice",
    "Box",
    "Mom's Key",
    "Mom's Eyeshadow",
    "Iron Bar",
    "Midas' Touch",
    "Humbling Bundle",
    "Fanny Pack",
    "Sharp Plug",
    "Guillotine",
    "Ball of Bandages",
    "Champion Belt",
    "Butt Bombs",
    "Gnawed Leaf",
    "Spider Baby",
    "Guppy's Collar",
    "Lost Contact",
    "Anemic",
    "Goat Head",
    "Ceremonial Robes",
    "Mom's Wig",
    "Placenta",
    "Old Bandage",
    "Sad Bombs",
    "Rubber Cement",
    "Anti-Gravity",
    "Pyromaniac",
    "Cricket's Body",
    "Gimpy",
    "Black Lotus",
    "piggy Bank",
    "Mom's Perfume",
    "Monstro's Lung",
    "Abaddon",
    "Ball of Tar",
    "Stop Watch",
    "Tiny Planet",
    "Infestation 2",
    "E-Coli",
    "Death's Touch",
    "Key Piece 1",
    "Key Piece 2",
    "Experimental Treatment",
    "Contact From Below",
    "Infamy",
    "Trinity Shield",
    "Tech.5",
    "20/20",
    "Blue Map",
    "BFFS!",
    "Hive Mind",
    "There's Options",
    "Bogo Bombs",
    "Starter Deck",
    "Little Baggy",
    "Magic Scab",
    "Blood Clot",
    "Screw",
    "Hot Bombs",
    "Fire Mind",
    "Missing No.",
    "Dark Matter",
    "Black Candle",
    "Proptosis",
    "Missing Page 2",
    "Smart Fly",
    "Dry Baby",
    "Juicy Sack",
    "Robo-Baby 2.0",
    "Rotten Baby",
    "Headless Baby",
    "Leech",
    "Mystery Sack",
    "BBF",
    "Bob's Brain",
    "Best Bud",
    "Lil' Brimstone",
    "Isaac's Heart",
    "Lil' Haunt",
    "Dark Bum",
    "Big Fan",
    "Sissy Longlegs",
    "Punching bag",
    "How To Jump",
    "D100",
    "D4",
    "D10",
    "Blank Card",
    "Book Of Secrets",
    "Box Of Spiders",
    "Red Candle",
    "The Jar",
    "Flush!",
    "Satanic Bible",
    "Head Of Krampus",
    "Butter Bean",
    "Magic Fingers",
    "Converter",
    "Pandora's Box",
    "Unicorn Stump",
    "Taurus",
    "Aries",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
    "Eve's Mascara",
    "Judas' Shadow",
    "Maggy's Bow",
    "Holy Mantle",
    "Thunder Thighs",
    "Stranger Attractor",
    "Cursed Eye",
    "Mysterious Liquid",
    "Gemini",
    "Cain's Other Eye",
    "???'s Only Friend",
    "Samson's Chain",
    "Mongo Baby",
    "Isaac's Tears",
    "Undefined",
    "Scissor",
    "Breath Of Life",
    "The Polaroid",
    "The Negative",
    "The Ludovico Technique",
    "Soy Milk",
    "Godhead",
    "Lazarus' Rag",
    "The Mind",
    "The Body",
    "The Soul",
    "Dead Onion",
    "Broken Watch",
    "The Boomerang",
    "Safety Pin",
    "Caffeine Pill",
    "Torn Photo",
    "Blue Cap",
    "Latch Key",
    "Match Book",
    "Synthoil",
    "A Snack",
    "Diplopia",
    "Placebo",
    "Wooden Nickel",
    "Toxic Shock",
    "Mega Bean",
    "Glass Bean",
    "Bomber Boy",
    "Crack Jacks",
    "Mom's Pearls",
    "Car Battery",
    "Box Of Friend",
    "The Wiz",
    "8 Inch Nails",
    "Incubus",
    "Fate's Reward",
    "Lil' Chest",
    "Sworn Protector",
    "Friend Zone",
    "Lost Fly",
    "Scatter Bombs",
    "Sticky Bombs",
    "Epiphora",
    "Continuum",
    "Mr. Dolly",
    "Curse Of The Tower",
    "Charged Battery",
    "Dead Eye",
    "Holy Light!",
    "Host Hat",
    "Restock",
    "Bursting Sack",
    "No. 2",
    "Pupula Duplex",
    "Pay To Play",
    "Eden's Blessing",
    "Friendly Ball",
    "Tear Detonator",
    "Lil Gurdy",
    "Bumbo",
    "D12",
    "Censer",
    "Key Bum",
    "Rune Bag",
    "Seraphim",
    "Betrayal",
    "Zodiac",
    "Serpent's Kiss",
    "Marked",
    "Tech X",
    "Ventricle Razor",
    "Tractor Beam",
    "God's Flesh",
    "Maw Of The Void",
    "Spear Of Destiny",
    "Explosivo",
    "Chaos",
    "Spider Mod",
    "Farting Baby",
    "GB Bug",
    "D8",
    "Purity",
    "Athame",
    "Empty Vessel",
    "Evil Eye",
    "Lusty Blood",
    "Cambion Conception",
    "Immaculate Conception",
    "More Options",
    "Crown Of Light",
    "Deep Pockets",
    "Succubus",
    "Fruit Cake",
    "Teleport 2.0",
    "Black Powder",
    "Kidney Bean",
    "Glowing Hour Glass",
    "Circle Of Protection",
    "Sack Head",
    "Night Light",
    "Obsessed Fan",
    "Mine Crafter",
    "PJs",
    "Head Of The Keeper",
    "Papa Fly",
    "Multidimensional Baby",
    "Glitter Bombs",
    "My Shadow",
    "Jar Of Flies",
    "Lil' Loki",
    "Milk!",
    "D7",
    "Binky",
    "Mom's Box",
    "Kidney Stone",
    "Mega Blast"
];

var Description = [
    "+0.7 cadence de tir.",
    "Donne trois larmes mais la stat \"tears\" diminue beaucoup.",
    "Donne des larmes psychiques",
    "+0.5 Dégâts, puis multiplie vos dégâts actuels par 1.5. Vos ennemis sont davantage renvoyés en arrière avec vos larmes.",
    "+1.5 de portée supplémentaire. +0.6 de vitesse de larmes. +1 de hauteur de tir. Vos larmes reviennent vers vous à mi-chemin de leur course.",
    "+1.5 Cadence de tir -15.78 Portée +0.45 Hauteur de tir.",
    "+1.0 Dégâts. 1.5x de multiplication de dégâts si vous possédez déjà le Book of Belial.",
    "Un familier qui suit Isaac et tire des larmes normales.",
    "Les mouches n'ont plus de comportement aggressifs envers Isaac",
    "Les mouches n'ont plus de comportement aggressifs envers Isaac",
    "Vous donne une vie supplémentaire.",
    "+1 Coeur Rouge +0.3 Dégâts 1.5x de multiplication de dégâts. +5.25 Portée de tir +0.3 Vitesse de déplacement. +0.5 Hauteur de tir. Isaac devient plus grand. Vous soigne entiérement.",
    "Inflige l'altération d'état Poison lorsque l'on entre en contact avec un ennemi.",
    "+0.6 Vitesse de déplacement",
    "+1 Coeur rouge Soigne tous les coeurs rouges manquant",
    "+ 2 Coeur rouge Vous rend tous vos coeurs rouges manquants",
    "+99 Clés",
    "+99 pièces",
    "+10 bombes",
    "Permet à Isaac de voler.",
    "Affiche tous les lieux spéciaux de la map.",
    "+1 Coeur rouge",
    "+1 Coeur rouge",
    "+1 Coeur rouge",
    "+1 Coeur rouge",
    "+1 Coeur rouge",
    "+0.3 Vitesse de Déplacement",
    "+0.3 Vitesse de Déplacement",
    "+5.25 Portée de tir. +0.5 Hauteur de tour ",
    "+5.25 Portée de tir. +0.5 Hauteur de tour ",
    "+5.25 Portée de tir. +0.5 Hauteur de tour ",
    "+0.7 Cadence de tir",
    "Donne des ailes d'ange à Isaac lui permettant de voler pendant une salle.",
    "Vous donne +2 Dégâts. 1.5x de multiplication de dégâts si vous possédez déjà le Blood of the Martyr.",
    "Inflige de gros dégats à tous les ennemis dans la salle",
    "Isaac fait caca. Voilà.",
    "Vous posséder maintenant une énorme bombe qui inflige de gros dégats",
    "Tire 10 larmes dans un cercle autour d'Isaac",
    "Géle temporairement tous les ennemis dans la salle.",
    "Isaac posséde une ceinture explosive qu'il peut activer à volonté, lui enlevant un demi coeur à chaque fois et blessant tous les ennemis aux alentours.",
    "Effraie tous les ennemis de la salle, qui fuient Isaac pendant quelques secondes.",
    "Vous pouvez tirer une bombe empoisonnée qui explose et empoisonne vos ennemis.",
    "Téléporte Isaac dans une salle aléatoire de l'étage",
    "Soigne Isaac d'un coeur entier.",
    "+1 de chance.",
    "Une cible apparaît au sol et peut être controllée. Après quelques secondes, ou après avoir réactivé l'item, un gros missile tombe au sol infligeant d'importants dégâts.",
    "Les larmes d'Isaac traversent maintenant les ennemis.",
    "Tir un laser similaire à Brimstone dans une direction",
    "+1 Dégâts",
    "+1.0 Dégâts",
    "Les larmes d'Isaac sont remplacées par des bombes. Réduit votre Cadence de tir",
    "Tous les objets au sol sont attirés vers vous.",
    "Révèle la disposition des salles sur la carte, mais pas leur rôle.",
    "Vous avez une chance de tirer une autre larme venant de l'arrière de votre tête.",
    "Crée une flaque jaune de \"limonade\" autour d'Isaac qui blesse tous les ennemis qui marchent dessus.",
    "Isaac posséde maintenant une mouche qui gravite autour de lui et inflige des dégats aux ennemis",
    "Vous rend temporairement invincible",
    "Permet à Isaac de passer au-dessus des trous d'une case grace à une échelle.",
    "Vous soigne d'un demi-coeur lorsque vous tuez 6.",
    "Vous pouvez désormais surcharger vos items au double de leur capacité. Vous permet donc d'utiliser deux fois un objet de suite.",
    "Les objets dans les magasins voient leur prix divisé par 2, arrondit à la somme inférieure.",
    "Fait tomber une pluie de bombes à des positions aléatoires sur une salle.",
    "Ralentit tous les ennemis et leurs projectile dans une salle.",
    "Un familier suivant Isaac et tirant des larmes rouges à son rythme",
    "Remplace les larmes d'Isaac par un laser.",
    "Isaac peut dorénavant charger ses tirs en gardant la touche enfoncée. ",
    "+1.0 Dégâts +0.4 Vitesse de déplacement",
    "+0.3 Vitesse de déplacement Isaac devient plus petit.",
    "+3 Coeur bleus  + Foi",
    "Un Cube de Chair tourne autour d'Isaac à la manière du Ball of Bandages. Si vous en obtenez un second, se change en boule rouge qui peut tirer sur les ennemis. Si vous en obtenez un troisième, se change en Meat Boy, poursuivant les ennemis et leur inflige des dégats. Un augmentera la taille et les dégâts de Meat Boy.",
    "+25 pièces",
    "Toutes les pilules ont maintenant des effets neutres ou positifs et sont identifiées. Donne une pilule dans l'inventaire. Soigne de deux coeurs rouges.",
    "Révèle l'entrée des Salles Secretes adjacentes. Ouvre le passage sans avoir à utiliser d'explosifs.",
    "Donne une invincibilité temporaire à Isaac lui permettant d'infliger des dégats de corps à corps.",
    "Vous donne un coeur bleu. Si vous ne l'avez pas encore rencontré, le boss de cet étage sera un Cavalier de l'Apocalypse (à condition de ne pas les avoir déjà tue).",
    "+1 Coeur bleu +1.0 Dégâts +0.2 Vitesse de déplacement",
    "+2 Coeurs bleus +0.5 Dégâts +0.7 Cadence de tir",
    "Ne laisse qu'un seul coeur rouge à Isaac (ne touche pas aux coeurs bleus et noirs) mais lui donne 8 huit vies supplémentaires. Chaque fois qu'Isaac meurt, vous revenez à la vie avec un seul coeur dans la salle précédente.",
    "Donne des ailes de démon à Isaac lui permettant de voler.",
    "Change Isaac en démon lui donnant : +0.7 Dégâts -0.18 de réduction de vitesse. +1 coeur noir. Vous pouvez écraser les obstacles.",
    "Fait apparaitre une trappe menant au niveau suivant. A une chance sur dix de mener au Marché Noir.",
    "Donne à Isaac une carte de tarot aléatoire",
    "Monstro atterit sur un ennemi aléatoire, lui infligeant d'énormes dégats.",
    "Vous avez une chance de tirer dans les 4 directions",
    "Un familier qui suit Isaac et charge dans la direction de ses larmes, traversant les ennemis et leur infligeant des dégats.",
    "Les larmes d'Isaac peuvent maintenant ralentir les ennemis",
    "+1 Dégât",
    "Révèle la position des salles secrètes adjacentes.",
    "+1 Coeur rouge +2 Coeurs bleus",
    "Isaac se change en Pacman et tous les ennemis le fuient. Isaac est invincible, ne peut pas tirer mais inflige des dégats au corps à corps.",
    "Fait apparaitre une pièce de monnaie aléatoire toutes les 2 salles.",
    "Un familier suivant Isaac et tirant des lasers similaire à Technology",
    "Un familier qui suit Isaac et donne un coeur rouge toutes les deux salles.",
    "Fait apparaitre un objet aléatoire dans la salle (Bombes, Coeurs, Piéces, Pilules, Batteries ou Cartes de Tarot).",
    "Fait apparaitre un Coeur bleu toutes les 5 salles",
    "Un familier qui suit Isaac et tire des larmes de goudron qui ralentissent les ennemis ainsi que leurs projectiles.",
    "Un familier qui suit Isaac et tire des larmes à tête chercheuse",
    "+1 Coeur rouge +0.3 Dégâts +0.2 Cadence de tir +0.25 Portée de tir +0.3 Vitesse de déplacement +0.5 Hauteur de tir",
    "Vous donne une pilule aléatoire.",
    "Vos larmes ont maintenant une chance d'empoisonner vos ennemis.",
    "Les larmes d'Isaac se séparent maintenant en deux lorsqu'elles touchent leur cible.",
    "Lorsqu'il est utilisé change tous les objets sur piedestal dans la salle",
    "+5 Bombes. Vos bombes ont une plus grande portée.",
    "Coupe la tête d'Isaac, laissant son corps courir et infliger des dégats de contact pendant que vous controlez la tête afin de tirer.",
    "Diminue les dégâts reçus et les arrondit au demi-coeur inférieur.",
    "+0.04 Dégâts par piéce.",
    "Vos larmes ont maintenant une chance aléatoire de geler un ennemi.",
    "Isaac fait un pet empoisonnant les ennemis à proximité.",
    "Un ange gravite autour d'Isaac, infligeant des dégats au contact, bloquant les larmes ennemies et augmentant la vitesse de tous vos objets orbitaux.",
    "Un familier qui suit Isaac et tire automatiquement sur les ennemis proches",
    "Vos larmes sont remplacées par un couteau que vous chargez et lancez sur une courte distance. Il inflige d'énormes dégâts.",
    "Isaac tire maintenant des larmes spectrales qui traversent les obstacles.",
    "Vos objets activable ont une barre de rechargée automatiquement après utilisation.",
    "Lorsque Isaac prend des dégâts, un oiseau apparait et attaque les ennemis proches dans la salle. Il disparait lorsque l'on sort de la salle.",
    "Isaac abandonne ses larmes pour un laser traversant toute la salle, transperçant les ennemis et le décors, infligeant d'énormes dégâts. Le laser doit être chargé en maintenant la touche de tir. Le laser part lorsque l'on relâche la touche.",
    "+1 Coeur rouge. Soigne jusqu'à 5 coeurs rouges.",
    "+1.7 Cadence de tir. +0.3 Vitesse de déplacement. Réduit considérablement vos dégâts (Dégâts x 0.9 - 0.4).",
    "+1 Coeur rouge. +0.3 Dégâts. +0.25 Portée de tir. -0.1 Vitesse de déplacement. +0.5 Hauteur de tir.",
    "Lorsque vous n'avez plus qu'un demi-coeur, vous vous transformez en 'Whore of Babylon' et gagnez +1.5 Dégâts et +0.3 Vitesse de déplacement.",
    "Vous donne un familier aléatoire pendant la durée d'une salle.",
    "Fait l'effet d'un Objet Activable aléatoire.",
    "+ 5 bombes. Toutes les bombes d'Isaac sont maintenant attirées par les ennemis.",
    "Augmente les dégâts d'Isaac de 1.2 le temps d'une salle en échange d'un coeur rouge.",
    "Ne s'active qu'une seule fois et rafraichit entiérement le niveau, les monstres et les items qui s'y trouvent.",
    "Une mouche gravite autour d'Isaac infligeant des dégats aux ennemis qu'elle touche.",
    "+2 Coeur rouges. -0.2 de vitesse de déplacement. Vous fait grossir.",
    "Isaac vole et fixe sa vitesse à 1.5. lorsqu'il est activé, il dash dans une direction, infligeant des dégats aux ennemis touchés.",
    "Vous donne des bombes aléatoirement lorsque vous terminez une salle.",
    "Vos larmes gagnent en dégats et en taille proportionnellement au temps qu'elles ont passé affichées à l'écran.",
    "À chaque activation, vous enlève un coeur rouge pour vous donner 3 coeurs bleus.",
    "Lorsqu'il est ramassé, augmente vos chance de trouver des coffres de tous types mais diminue vos chances de trouver des clés.",
    "Consomme un demi coeur rouge et fait apparaitre des piéces au sol.",
    "Place un appât sur le sol qui attire les ennemis vers lui, puis explose.",
    "+5 Bombes. les bombes n'explosent plus avec le temps mais sur activation de l'objet.",
    "+1 Coeur rouge +0.3 Dégâts",
    "Isaac peut maintenant transporter deux trinkets à la fois.",
    "+ 5 bombes. Toutes vos bombes empoisonnent les ennemis.",
    "Fait apparaitre 7 piéces de valeur aléatoire au sol.",
    "Une fois par salle, lorsqu'Isaac subit des dégâts qui le laissent à un demi-coeur rouge ou moins, il encaisse le dégât et reçoit un coeur bleu.",
    "+0.3 Vitesse de Déplacement. +0.2 Vitesse de Projectile",
    "Un mendiant qui suit Isaac et ramasse les piéces qui tombent pour les échanger potentiellement avec d'autres objets collectables.",
    "Fait apparaitre quelques mouches bleues.",
    "Vous donne un coeur eternel.",
    "Vous permet de détruire toutes les pierres d'une salle en marchant dessus. Vous ne pouvez pas tirer tant qu'Isaac brandit sa pioche. Appuyez à nouveau sur le bouton d'action pour le désactiver.",
    "Lorsqu'Isaac se fait toucher, des mouches  bleues apparaissent et attaquent les ennemis.",
    "Les larmes d'Isaac sont remplacées par des bombes empoisonnées qui explosent au contact d'un ennemi ou au sol. Réduit votre Cadence de tir. +13.0 Hauteur de tir",
    "Isaac a une faible chance de tirer une dent au lieu d'une larme. Les dents font énormément plus de dégâts.",
    "Infliger des dégâts à un ennemi vous donne une chance d'invoquer une mouche bleue attaquant les ennemis.",
    "Isaac tire un laser qui inflige continuellement des dégâts. -35% de Dégâts",
    "Vous tirez maintenant 4 larmes à la fois mais réduit grandement votre débit de larmes.",
    "+2 Dégâts de l'oeil gauche d'Isaac.",
    "Un compagnon parcourt la salle en diagonale inflgeant des dégats aux ennemis qu'il touche.",
    "Lorsque vous prenez des dégats, recharge votre objet activable d'une barre.",
    "Chaque fois que vous prenez des dommages, vos dégâts augmente le temps d'un étage. Cet objet reset à chaque nouveau niveau.",
    "Lorsqu'il est utilisé, dévoile entiérement la map puis donne une carte, une rune ou un coeur bleu.",
    "Permet à Isaac de voler. Isaac tire des larmes spectrales",
    "Plusieurs rayons de lumière tombent du ciel à des positions aléatoires, blessant tous les ennemis touchés.",
    "Lorsque vous mourrez, vous revenez à la vie en tant que Blue Baby avec 3 coeurs bleus.",
    "Lorsque vous prenez des dégats, vous avez une chance de devenir invulnérable pendant quelques secondes",
    "Un familier suit Isaac et tire des larmes spectrales qui traversent les obstacles.",
    "Isaac peut tirer une flamme bleue en ligne droite infligeant d'énormes dégats sur son passage. Se recharge ensuite en quelques secondes.",
    "+1.0 Dégâts. +0.23 de vitesse de tir supplémentaire.",
    "Lorsqu'il est utilisé, change tous les collectables dans la salle.",
    "Un familier suit Isaac et tire des larmes deux par deux en V.",
    "Isaac ne tire plus de larmes. Lorsqu'il cherche à tirer, une cible apparait au sol et peut être déplacée avec les touches de tir. Trois secondes après la création de la cible, un missile tombe et inflige d'énormes dégâts.",
    "Augmente considérablement vos dégats. Réduit considérablement votre débit de larmes.",
    "Une ombre suit Isaac et écrase aléatoirement certains ennemis, leur infligeant des dégats.",
    "Inflige de léger dégâts à tous les ennemis dans la salle et les ralentit",
    "Donne à Isaac un couteau gravitant autour de lui, bloquant les projectiles et faisant énormément de dégâts.",
    "Les chances d'obtenir des coeurs bleus à la fin de chaque salle sont considérablement augmentées.",
    "Un familier suit Isaac et tire des larmes aux effets aléatoires.",
    "Ouvre toutes les portes de la salle dans laquelle vous vous trouvez.",
    "+1 Coeur rouge. +0.16 Vitesse des Projectiles",
    "Une machine à sous portative qui consomme une pièce contre une chance de gagner autre chose..",
    "Lorsqu'Isaac est touché, il répand une flaque d'eau bénite au sol qui inflige des dégats à tous les ennemis qui la touchent.",
    "+1 Coeur blanc. Isaac vole désormais.",
    "Lorsqu'il est touché, Isaac lache une caisse empoisonnant les ennemis à proximité.",
    "Charge dans une direction et fait tomber des rayons de lumières. Permet à Isaac de voler tant qu'il tient cet objet.",
    "+1 Coeur rouge; Dégâts multipliés par 2.3, puis augmenté de 1; -0.4 Cadence de tir; -0.25 Vitesse des larmes; +0.375 Portée; +0.75 Hauteur de larme; Soigne tous les coeurs rouges; Les larmes deviennent énormes et à tête chercheuse.",
    "+0.7 Débit de Larmes; +0.16 Vitesse des projectiles; Fait tirer des larmes rouges",
    "+1 Coeur rouge. Donne à Isaac la capacité de voler.",
    "Donne à Isaac la possibilité de voler. Isaac tire des larmes spectrales qui traversent les obstacles.",
    "Vous inflige un demi-coeur de dégâts et blesse tous les ennemis dans la salle.",
    "Une boule de poil suit Isaac, qui peut être balancée autour de vous en fonction de votre vitesse de déplacement et qui inflige des dégats aux ennemis touchés. Lorsqu'elle tue un ennemi elle grossit progressivement pour infliger davantage de dégats.",
    "Un familier volant qui copie les mouvements d'Isaac à l'opposé.",
    "+1 Coeur rouge; +0.3 Dégâts; +0.2 Cadence de tir; +0.5 Portée de tirs; +0.2 Vitesse de déplacement; Soigne complètement les coeurs rouges.",
    "+99 Bombes.",
    "Vous tirez des larmes aléatoires à chaque salle.",
    "Donne des larmes à tête chercheuse à Isaac le temps d'une salle.",
    "+1 Coeur; +0.3 Dégâts.",
    "+0.16 Vitesse de projectile; Fait apparaitre une carte de tarot aléatoire au sol.",
    "Fait tomber 4 pilules aléatoire sur le sol.",
    "+2 Coeurs bleus; +0.4 Cadence de tir",
    "+0.5 Dégâts; +0.25 Portée de tir; +0.5 Hauteur de tir.",
    "Fait apparaître un objet collectable de chaque sorte sur le sol.",
    "+2 clés; Les coffres contiennent bien plus d'objets",
    "Vos larmes ont maintenant une chance de charmer les ennemis.",
    "+0.3 Dégâts; Les larmes peuvent maintenant rendre vos ennemis confus, les forçant à se déplacer aléatoirement pendant un court instant.",
    "Les ennemis qui touchent Isaac sont maintenant changés en or, les pétrifiant quelques secondes. S'ils sont détruits, ils laisseront tomber entre 1 et 4 piéces.",
    "Les objets collectables apparaissent en double.",
    "Lorsqu'Isaac est touché, il y a une chance qu'il lache un objet collectable.",
    "Si Isaac possède un Objet Activable déchargé, appuyer sur la touche d'utilisation de l'objet le rechargera en échange de 2 coeurs de dégâts.",
    "+1.0 Dégâts; +0.16 Cadence de Tir; La tête d'Isaac se détache de son corps et gravite autour de vous, à la manière d'une mouche. La tête continue à tirer.",
    "Une boule de bandages tourne autour d'Isaac à la manière du Cube of Meat. Si vous en obtenez une seconde, se change en boule rose qui peut tirer et charmer les ennemis. Si vous en obtenez une troisième, se change en Bandage Girl, poursuivant les ennemis et leur tirant dessus. Une quatrième boule de bandages augmentera la taille et les dégâts de Bandage Girl.",
    "+1.0 Dégâts; Augmente la chance de croiser des ennemis champions.",
    "+5 Bombes; Vos bombes infligent des dégâts et étourdissent temporairement tous les ennemis dans la salle lorsqu'elles explosent",
    "Si Isaac est immobile pendant une seconde, il se change en pierre et devient invincible tant qu'il ne bouge pas.",
    "Lorsqu'Isaac prend des dégâts, il génère une araignée offensive",
    "Lorsqu'Isaac meurt, il a 50% de chance de revenir à la vie avec 1/2 coeur rouge.",
    "-0.15 Cadence de tir; Les larmes d'Isaac possédent maintenant une aura qui bloque les projectiles et se détruisent mutuellement.",
    "+5 Portée de tir; Isaac laisse une trainée de sang derriére lui s'il est touché.",
    "Vous avez 100% de chance d'avoir accès au Devil Rooms et Angels Rooms depuis la salle du boss.",
    "+3 Coeurs noirs.; +1 Dégâts à chaque fois que vous terminez un niveau; +1 Pêché",
    "Il y a maintenant une chance qu'Isaac fasse apparaitre une araignée chaque fois qu'il tire, allant jusqu'à 5 araignée par salle.",
    "+1 Coeur rouge; Isaac récupère des coeurs rouges à intervales réguliers.",
    "+1 Coeur rouge; Lorsque vous vous faites toucher, vous avez une faible chance de faire apparaitre un coeur rouge sur le sol.",
    "+5 Bombes; Lorsqu'une bombe explose, elle relâche un cercle de larmes qui infligent des dégâts aux ennemis.",
    "Les larmes d'Isaac rebondissent sur les obstacles.",
    "+0.32 Cadence de tir; Vos larmes lévitent sur place tant que vous maintenez le bouton de tir",
    "+5 Bombes; Toutes les explosions vous soignent d'un coeur au lieu de vous blesser.",
    "+0.16 Dégâts; -10.0 Portée; À l'impact, vos larmes se séparent en 4 petites larmes.",
    "Lorsqu'Isaac est touché, il y a une chance qu'un coeur bleu ou noir tombe au sol.",
    "+1 Coeur rouge; +1 Coeur noir; +1 Coeur bleu",
    "+3 piéces lorsque vous le ramassez. Quand vous vous faites toucher, fait tomber entre 1 et 2 piéces au sol.",
    "+0.16 Cadence de tir; Vos larmes ont 15% de chance d'effrayer les ennemis.",
    "Permet de charger un nuage de larme similaire aux tirs de Monstro.",
    "+1.5 Dégâts; + 0.2 de Vitesse de déplacement; +1 Evil; Supprime tous vos coeurs rouges et vous donne 6 coeurs noirs; Vos larmes peuvent dorénavant effrayer les ennemis.",
    "Vos larmes ont une chance de ralentir les ennemies. Isaac laisse une trainée de goudron derriére lui, ralentissant elle aussi les ennemis.",
    "A l'entrée de chaque salle, peut ralentir ou accélérer tous les ennemis.",
    "Augmente énormément la Portée; Les larmes gravitent désormais autour d'Isaac",
    "Lorsque vous tuez un ennemi, fait apparaître entre 1 et 2 araignées bleues à l'endroit où l'ennemi meurt.",
    "Les ennemis basiques sont changés en defecation lorsqu'ils vous touchent",
    "+1.5 Dégâts; -0.3 de débit de larmes; Les larmes d'Isaac se changent en faux qui traversent les ennemis.",
    "La première partie de la clé menant à Mega Satan.",
    "La seconde partie de la clé menant à Mega Satan.",
    "Augmente toutes vos statistique de 1 puis les mélangent toute.",
    "Double vos loots, comprenant les coffres et les coeurs bleus. Plus de chance de devoir affronter des doubles boss dans la même salle.",
    "Isaac posséde maintenant un masque pouvant annuler certain dégats venant de devant.",
    "Isaac brandit devant lui un bouclier bloquant les projectiles.",
    "Place un laser sur le front d'Isaac qui tire aléatoirement des lasers à intervals irréguliers.",
    "Isaac tire avec ses deux yeux à la fois.",
    "Vous dévoile l'emplacement des salles secrétes et super secrétes.",
    "Augmente la taille et les dégats des familiers d'Isaac.",
    "Vos araignées et mouches grossissent et infligent plus de dégats.",
    "Lorsqu'un boss meurt, il laisse deux récompenses au lieu d'une. Isaac ne peut prendre que l'une d'elles.",
    "Chaque bombe que vous ramassez vous donne en fait 2 bombes.",
    "Isaac peut porter deux cartes de tarot à la fois.",
    "Vous permet de transporter 2 pilules; Fait apparaitre une pilule au sol; Toutes cartes de tarot sont remplacées par des pilules.",
    "+1 Coeur Rouge; +1 Chance",
    "+1.0 Dégâts; +5 Portée de tir; Ces stats ne s'appliquent qu'aux larmes venant de l'oeil gauche d'Isaac.",
    "+0.5 Cadence de tir; +0.2 Vitesse des projectiles",
    "+5 Bombes; Toutes vos bombes laissent une flamme au sol lorsqu'elle explosent.",
    "Les larmes d'Isaac enflamment maintenant les ennemis, infligeant progressivement des dégats. Certaines larmes peuvent également exploser au contact, laissant une flamme au sol.",
    "Au début de chaque étage, cet objet change tous les objets de votre build.",
    "+1.0 Dégâts; Les larmes ont maintenant une chance d'effrayer les ennemis.",
    "+1 Coeur Noir; +1 Evil; Vous ne pouvez plus être victime de malédictions de salles.",
    "Réduit grandement votre portée mais vous tirez d'énormes larmes qui rétrécissent et s'écrasent au sol rapidement.",
    "+1 Coeur noir; +1 Evil",
    "Une mouche qui tourne autour d'Isaac et bloque les projectiles ennemis. Lorsqu'Isaac se fait toucher, la mouche devient offensive et va attaquer les ennemis.",
    "Un familier qui suit Isaac et bloque les tirs ennemis. Lorsque le Dry Baby est touché il y a alors une forte chance qu'il déclenche l'effet du Necronomicon, blessant tous les ennemis dans la salle.",
    "Un familier qui suit Isaac laissant une trainée blanche derrière lui, ralentissant les ennemis. Lache une araignée au sol lorsque vous terminez une salle.",
    "Un familier tirant des lasers similaire à Technology. Il peut être déplacé à la manière d'Isaac, mais avec les boutons de tir.",
    "Un familier tirant des mouches offensives. Ne peut créer qu'une mouche à la fois.",
    "Un familier suit Isaac et laisse une traînée de sang derrière lui qui inflige des dégâts aux ennemis qui marchent dessus.",
    "Une sangsue accompagne Isaac et attaque les ennemis, vous rendant parfois un demi coeur lorsqu'elle tue un ennemi.",
    "Donne un objet collectable aléatoire toutes les deux salles.",
    "Une mouche explosive vole dans la salle et rebondit sur les parois. Lorsqu'elle touche un ennemi, elle explose. Elle réapparait sur le terrain après quelques secondes.",
    "Un cerveau vert vous suit et peut être tiré en même temps que vos larmes. Il explose au contact d'un ennemi, infligeant des dégâts et l'empoisonnant. Réapparait quelques secondes après son explosion",
    "Si Isaac est touché, une mouche apparait et tourne autour de lui rapidement pour intercepter les projectiles ennemis.",
    "Un familier qui suit Isaac et charge un laser brimstone.",
    "Lorsqu'Isaac est sensé prendre un dégât, fait apparaître un coeur qui suit Isaac. Si le coeur est touché, Isaac prendra les dégâts.",
    "Un petit fantôme qui suit Isaac, attaquant les ennemis proches et les effrayant.",
    "Un familier qui ramasse les coeur rouges au sol pour vous donner des coeurs bleus ou noirs.",
    "Une grosse mouche gravite autour d'Isaac, bloquant les projectiles ennemis.",
    "Une araignée bleue qui se promènent dans la salle et créer des arraignées offensives aléatoirement",
    "Fait apparaitre un appat qui se promène et que les ennemis prennent aléatoirement pour cible.",
    "Isaac peut maintenant bondir, de la même manière que certains ennemis. Si votre personnage vole déjà, se transforme en dash.",
    "Lorsqu'il est utilisé, change tous les items que vous possédez, ainsi que tous les objets dans la salle.",
    "Lorsqu'il est utilisé, le D4 change tous les autre items de votre build en d'autres objets.",
    "Lorsqu'il est utilisé, change tous les ennemis de cet étage en d'autres du même étage.",
    "Copie l'effet de la carte que vous avez en main.",
    "Lorsqu'il est utilisé, provoque l'effet de l'un de ces objets : Treasure Map, Compass ou Blue Map.",
    "Fait apparaître entre 2 et 4 araignées au sol.",
    "Tire une flamme rouge qui blesse les ennemis et ne disparait pas avec le temps.",
    "Vous pouvez stocker 4 coeurs rouges dont vous n'avez pas besoin. Appuyer sur la touche d'action libérera les coeurs au sol.",
    "Lorsqu'il est utilisé change tous les monstres (non boss) de la salle en caca, et tue instantanement dingle, dangle et brownie.",
    "Donne un Coeur noir.",
    "Tire des lasers brimstone dans les quatre directions infligeant d'énormes dégats. Les lasers ont une chance de tourner a 90°.",
    "Lorsqu'il est utilisé, Isaac lache une caisse sur les ennemis alentours et les projette en arrière.",
    "Dépense une piéce et inflige de faibles dégats dans toute la piéce.",
    "Convertit 2 de vos coeurs bleus ou noirs en 1 coeur rouge.",
    "Fait apparaitre des objets collectable en fonction du niveau dans lequel vous êtes : Basement 1 : 2 Coeurs bleus; Basement 2 : 2 bombes et 2 clés; Caves 1 : 1 Item de Boss; Caves 2 : 1 Item de Boss + 2 coeurs bleus; Depths 1 : 4 coeurs bleus; Depths 2 : 20 piéces; Womb 1 : 2 Items de Boss; Womb 2 : La Bible; Sheol : 1 Item de Devil Room + 1 coeur noir; Cathedral : 1 Item d'Angel Room + 1 coeur eternel; Dark Room : 1 piéces; The Chest : Rien.",
    "Rend Isaac invincible et offre +0.28 de vitesse de déplacement.",
    "-0.3 Vitesse de Déplacement; La vitesse de déplacement augmente de 0.065 par seconde; Lorsqu'Isaac atteint 2.0 de vitesse de déplacement, il devient invincible dans un effet similaire à My Little Unicorn.",
    "+0.25 Speed Up; Isaac inflige de légers dégâts devant lui",
    "+3 Coeurs bleus; Après s'être fait toucher une fois, Isaac ne prend plus que 50% des dégats dans cette salle.",
    "Isaac peut dorénavant écraser tous les obstacles (rochers, cacas, pots ou cranes).",
    "Lorsqu'Isaac se fait toucher, il a une chance de devenir invincible pendant quelques secondes.",
    "Vous donne 6 clés, 6 bombes et 6 piéces; Equilibre vos statistiques jusqu'à la fin de la partie.",
    "Les larmes d'Isaac appliquent le poison sur les ennemis à coup sûr.",
    "+0.2 Vitesse de déplacement; Les larmes transpercent les ennemis.",
    "+1 Coeur rouge; +0.5 Dégâts; +0.16 Cadence de Tir; +0.1 Vitesse de Déplacement; +1.5 Portée de tir; +0.1 Vitesse de Projectile; +1 clé; +1 bombe; +1 piéce.",
    "Laisse une trainée de larme derriére vous infligeant des dégâts aux ennemis",
    "+0.16 Cadence de tir; Vos larmes repoussent davantage vos ennemis.",
    "Dégâts multipliés par 2; Cadence de tir divisée par 2; -0.5 Vitesse de projectiles.",
    "Quand vous mourrez avec cet item, vous revenez à la vie en tant que \"Black Judas\" avec 7 Dégâts ",
    "+1 Coeur rouge; Les coeurs rouges vous soignent deux fois plus.",
    "Annule le premier coup que vous prenez dans chaque salle.",
    "+1 Coeur rouge; -0.4 Vitesse de Déplacement; Isaac peut déruire les rochers, les cacas , les champignons et les cranes en marchant dessus.",
    "Les ennemis et les objets à ramasser sont attirés par les larmes d'Isaac.",
    "Vous pouvez charger vos tirs pour tirer jusqu'à 4 larmes consécutives. Lorsque vous chargez vos larmes, le Curse Eye oscille entre le blanc et le noir. Si vous vous faites toucher lorsqu'il est noir, vous serez téléporté dans une autre salle.",
    "Lorsque les larmes d'Isaac touchent une cible elles laissent une marque verte au sol qui inflige des dégats aux ennemis se tenant dessus.",
    "Un familier est attaché à Isaac et cherche à attaquer les ennemis à proximité.",
    "Un familier qui se promène dans la salle et tire des larmes dans la même direction qu'Isaac.",
    "Devient un familier que vous pouvez controler en même temps que vos larmes.",
    "Un boule d'acier est attachée au pied d'Isaac. Elle tourne autour d'Isaac au rythme de ses mouvements et bloque les projectiles ennemis en plus d'infliger des dégâts.",
    "Un familier qui suit Isaac et copie l'un de vos autres familiers et prend sa place, en plus fort. Sans familier il tirera des larmes normales.",
    "Tire 8 larmes d'Isaac en cercle autour de lui.",
    "Téléporte aléatoirement Isaac dans l'une des salles suivantes : Item Room, Secret Room, Super Secret Room ou I AM ERROR Room.",
    "Détâche la tête d'Isaac de son corp. La tête d'Isaac continuera à tirer normalement mais restera sur place. Le joueur contrôle alors le corp.",
    "Lorsque vous maintenant la barre d'espace, l'objet se déchargera lentement. Lorsque la charge de l'objet est vide, vous êtes invincible. Lorsque la charge est à zéro, vous prenez des dégats si vous l'activez à nouveau.",
    "Si vous vous faites toucher alors que vous n'avez plus qu'un demi coeur rouge, créer un bouclier vous rendant invulnérable pendant de longues secondes. Permet d'accéder à The Chest après avoir tué Isaac.",
    "Si vous vous faites toucher alors que vous n'avez plus qu'un demi coeur rouge, inflige des dégats à tous les ennemis dans la salle. Permet d'accéder à la Dark Room après avoir tué Satan.",
    "Vos larmes sont remplacées par une grosse larme unique dont vous controlez le déplacement.",
    "-80% Dégâts; Cadence de tir très élevée",
    "+0.5 Dégâts; +1.2 de portée supplémentaire; -0.2 de réduction de débit de larmes; -0.3 de vitesse de larmes; +0.8 de hauteur de tir; Les larmes d'Isaac sont dorénavant à tête chercheuse et sont entourées d'une grande aura qui blesse les ennemis qu'elle frôle.",
    "Donne à Isaac une vie supplémentaire; Vous revenez à la vie sous forme de Lazarus II, avec une seul coeur rouge et l'item Anemic.",
    "Révèle l'entierté de la map, à Isaac, salles secrètes incluses, et ce à tous les étages du jeu.",
    "+3 Coeurs rouges.",
    "+2 Coeurs bleus; Les projectiles vont lentement dévier de leur trajectoire en approchant d'Isaac",
    "-0.25 Portée; -0,4 Vitesse de Projectiles; -0.5 Hauteur de tir; Les larmes d'Isaac deviennent plus larges et passent à travers les objets et les ennemis.",
    "Lorsque vous entrez dans une piéce, vous avez une chance aléatoire de ralentir ou d'accélerer la vitesse de tir et de déplacement de tous vos adversaires.",
    "Vous posséder maintenant un boomerang que vous pouvez jeter sur vos ennemis pour les paralyser.",
    "+5.25 Portée d'attaque; +0.16 Vitesse des projectiles; +1 Coeur noir; +0.5 Hauteur de larmes",
    "+0.3 Vitesse de déplacement; Isaac devient plus petit; Vous donne une pilule aléatoire.",
    "+0.7 Cadence de tir; +0.16 Vitesse des projectiles",
    "+1 Coeur rouge; +1 Cadence de tir; +1 Vitesse des projectiles",
    "+1 de chance; +1 coeur bleu; Fait apparaître 2 clés au sol.",
    "+1 Coeur noir; +3 Bombes",
    "+1.0 Dégâts; +5.25 Portée",
    "+1 Coeur rouge",
    
    //========================//
    //       AFTERBIRTH       //
    //========================//
    
    "Duplique tous les objets dans la salle.",
    "Copie l'effet de la pillule tenue par Isaac sans la consommer.",
    "Vous avez 50% de chance de faire apparaitre une pièce aléatoire.",
    "En entrant dans une salle, tous les ennemis subissent des dégâts et sont empoisonnés. Tuer des ennemis laisse une flaque de poison sur le sol.",
    "Fige tous les ennemis de la salle pendant quelques secondes. Inflige des dégâts et empoisonne tous les ennemis proches. Envoie une vague de piques face à Isaac.",
    "Réduit les PVs de Isaac et tire une larme géante faisant énormément de dégâts.",
    "+5 bombes; Les bombes explosent désormais dans une déflagration en forme de croix.",
    "+1 Coeur Rouge; Fait apparaitre un Trinket aléatoire",
    "+1.25 Portée de larmes; +0.5 Hauteur de larmes; +1 Chance",
    "Les objets activables déclenchent deux fois leur effet à l'utilisation.",
    "Créer des doubles de tous vos familiers, le temps d'une salle.",
    "Les larmes passent à travers les obstacles; Isaac tir des larmes en diagonale, des deux yeux à la fois.",
    "+1.5 Dégâts; Les larmes repoussent les ennemis",
    "Un familier démoniaque qui suit Isaac et ti exactement les mêmes larmes que lui.",
    "Un familier qui suit Isaac et tir des larmes infligeant autant de dégâts que celles d'Isaac",
    "Un familier faisant apparaitre des objets consommables aléatoire de temps en temps.",
    "Un ange qui gravite autour d'Isaac, bloquant les tirs ennemis et infligeant des dégâts au contact. Quand il interrompt un tir, il a une faible chance de laisser tomber un Coeur Blanc.",
    "Un mouche qui orbite autour d'Isaac à une distance modérée et inflige des dégâts aux ennemis.",
    "Un familier qui vole droit devant lui lorsque l'on entre dans une salle. Il se fixe au premier obstacle qu'il rencontre et tourne autour, infligeant des dégâts à tous les ennemis qu'il croise.",
    "+5 Bombes; Les bombes d'Isaac explosent en 2 à 4 petites bombes supplémentaires.",
    "+5 bombes; Les bombes s'accrochent aux ennemis et font apparaitre 2 à 4 araignées bleues si elles tuent un ennemi.",
    "Tant qu'il tire dans la même direction, la vitesse d'attaque d'Isaac augmente à chaque tir. Le bonus s'annule quand il tire dans une nouvelle direction.",
    "+2.25 Portée d'Attaque; +1.5 Hauteur de tir; Les larmes d'Isaac traversent les murs pour réapparaitre de l'autre côté de la salle.",
    "+0.7 Débit de larmes; +5.25 Portée de larmes; +0.5 Hauteur de larmes; Fait apparaitre 3 coeurs aléatoires au sol",
    "Lorsqu'Isaac subit des dégâts, fait apparaitre 6 trolls bombs dans la salle.",
    "Un familier qui laisse tomber une batterie toutes les 4 salles. Possède une faible chance de figer tous les ennemis quand il est touché.",
    "Augmente les dégâts de chaque tir consécutif, du moment qu'il touche un ennemi, un feu ou un caca. Si une larme ne touche rien, le bonus de dégât est remis à 0.",
    "Les larmes d'Isaac ont une faible chance d'être bénie. Les ennemis touchés par des larmes bénies se font attaquer par un rayon de lumière infligeant énormément de dégâts.",
    "Un chapeau qui immunise Isaac aux explosions. Possède une chance de nullifier les dégâts de tirs reçus, le crâne réplique alors en tirant 3 fois.",
    "Chaque fois qu'un objet est acheté dans un Shop, un autre vient prendre sa place.	",
    "Les araignées ne font plus de dégâts de contact à Isaac.",
    "Tirer de manière continu peut faire apparaitre une Bombe Caca.",
    "Les larmes d'Isaac sont bien plus grosses et passent à travers les obstacles.",
    "Toutes les portes qui devraient nécessiter une clé pour être ouverte se transforment en porte à pièces.",
    "+0.7 Débit de larmes; Lors de votre prochaine partie, vous commencerez avec un objet aléatoire.",
    "Permet de capturer un ennemi avant de le réutiliser plus tard.",
    "Fait exploser vos larmes en 6 autres larmes.",
    "Un familier qui fonce dans la direction dans laquelle tir Isaac après avoir été chargé. Il rebondit et inflige des dégâts à tous les ennemis qu'il traverse.",
    "Un mendiant familier qui évolue à force de ramasser des pièces.",
    "Transforme tous les rochers de la salles en d'autres objets (TNT, caca, bloc de métal, pot, crane, etc)",
    "Créer un encensoir suivant Isaac. L'encensoir créer une aura de lumière ralentissant tous les ennemis pris dedans.	",
    "Un familier ramassant les clés au sol et donnant des coffres aléatoires en échange.",
    "Un sac faisant apparaitre une rune toutes les 3 salles.",
    "Un familier suivant Isaac et lançant des larmes à tête chercheuses lents mais puissantes.",
    "Quand Isaac subit des dégâts, tous les ennemis sont charmés et s'attaquent entre eux.",
    "Donne un objet du Zodiac aléatoire différent à chaque étage.",
    "Isaac et ses larmes peuvent empoisonner au contact. Les ennemis empoisonnés peuvent faire apparaitre un coeur noir à leur mort.",
    "+0.7 Débit de larmes; +0.3 Hauteur de tir; +3.15 Portée; Une cible rouge contrôlable apparait au sol. Isaac ne s'arrête plus de tirer et vise la cible.",
    "Les larmes sont remplacées par cercles de lasers traversant les ennemis. Les tirs peuvent être chargés pour augmenter la taille du cercle.",
    "Fait apparaitre alternativement un trou orange et un trou bleu.",
    "+0.5 Débit de larmes; +5.25 Portée; +0.16 Vitesse de larmes; +0.5 Hauteur de tir; Isaac émet un rayon de lumière bleu droit devant lui. Les larmes suivent la direction du rayon, même en cas de mouvement.",
    "Les larmes d'Isaac peuvent réduire la taille des ennemis. Les ennemis miniaturisés ont peur d'Isaac et peuvent être écrasés en marchant dessus.",
    "+1 Dégâts; +0.5 Hauteur de tir; Après avoir tiré pendant 3 secondes consécutives, créer un cercle de dégâts noir autour d'Isaac.",
    "Isaac tient une épée qu'il peut diriger autour de lui pour infliger des dégâts au contact.",
    "Les larmes d'Isaac peuvent se fixer aux ennemis avant de gonfler d'exploser.",
    "Mélange tous les pools d'items de votre partie. Fait apparaitre 1 à 6 objets consommables au sol.",
    "Un familier qui inflige des altérations d'états à tous les ennemis qu'il touche. Affiche les PVs des ennemis et les dégâts de chaque attaques en valeur numérique.",
    "Un familier qui suit Isaac et block les tirs adverses. Quand il reçoit un tir, le Farting Baby a de grandes chances de lacher un nuage de gaz repoussant / empoisonnant / charmant les ennemis.",
    "Un familier qui se déplace et rebondit dans la salle. Il applique un effet aléatoire à tous les ennemis qu'il touche. Quand GB Bug passe par dessus un consommable, possède une faible chance de reroll cet objet.",
    "Reroll les statistiques d'Isaac",
    "Boost aléatoirement une stat d'Isaac à chaque salle. L'effet se dissipe pour la salle en cours si Isaac subit des dégâts.",
    "Quand Isaac subit des dégâts, fait apparaitre temporairement un cercle noir infligeant des dégâts autour de lui. Les ennemis tués avec le cercle noir peuvent donner des coeurs noirs.",
    "+2 Coeurs Noirs; Quand Isaac n'a plus qu'un demi Coeurs Rouges, il vole et peut devenir temporairement invincible.",
    "Possède une faible chance de lancer un oeil copiant les tirs d'Isaac, à chaque tir. L'oeil est détruit s'il touche un obstacle.",
    "Isaac gagne des dégâts supplémentaires à chaque fois qu'il tue un ennemi dans une salle.",
    "Après avoir reçu un certain nombre de dégâts, fait apparaitre un familier démoniaque permanent.",
    "Après avoir récupéré un certain nombre de coeurs, fait apparaitre un familier angélique aléatoire.",
    "Les Item Rooms contiennent deux objets, mais seulement un peut-être récupéré.	",
    "Si Isaac a tous ses PV et ne s'est pas encore fait toucher dans une salle, ses larmes infligent le double de dégâts.",
    "Isaac peut désormer porter deux cartes/pillules/runes",
    "Un familier ayant une aura noir infligeant des dégâts à tous ceux piégés à l'intérieur. Si Isaac se tient dans l'Aura, il gagne +3 Dégâts. Il rebondit de murs en murs dans la salle. ",
    "Les larmes d'Isaac gagnent un effet aléatoire différent à chaque tir.",
    "Téléporte Isaac dans une salle qu'il n'a pas encore visité.",
    "Laisse une trainée noire derrière Isaac. Faire un cercle fermé avec la trainée noire créer un pentagrame dans le cercle, infligeant des dégâts continus aux ennemis se trouvant dessus.",
    "Lâche un gaz qui permet de charmer tous les ennemis proches.",
    "Vous téléporte dans la salle précédente et reset tout ce qu'il s'y est passé (perte ou gain de vie, kills, etc).",
    "Créer un cercle de dégâts autour d'Isaac. Possède une faible chance de renvoyer aux ennemis leurs propres tirs.",
    "Isaac a de très grandes chances de gagner des sacs d'objets au lieu des consommables classiques.",
    "Un cône de lumière émane d'Isaac dans la direction à laquelle il fait face. Les ennemis et les projectiles pris dans la lumière sont ralentis.",
    "Un familier copiant les mouvements d'Isaac avec un délai de 3 secondes. Inflige de lourds dégâts aux ennemis qu'elle touche.",
    "Place un baril d'explosif. Réutiliser l'objet pour faire exploser le baril.",
    "+4 Coeurs Bleus; Soigne complètement Isaac",
    "Lorsque les larmes d'Isaac touchent des ennemis, elles peuvent laisser tomber des pièces.",
    "Un familier bleu suivant Isaac et tirant automatiquement sur les ennemis proches.",
    "Un familier copiant les déplacements d'Isaac avec 2.5 secondes de retards. Vos tirs traversant le Baby sont doublés et plus puissants.",
    "+5 Bombes; Toutes les bombes laissent derrière elles des objets consommables.",
    "Pour chaque dégâts subit, Isaac fait apparaitre un ver noir attaquant les ennemis.",
    "Stock une mouche bleue par ennemi tué. Utiliser la jar relache les mouches sur les ennemis.",
    "Un familier qui suit Isaac et tire des larmes dans les 4 directions.",
    "Un verre de lait qui se brise lorsqu'Isaac reçoit des dégâts, ce qui augmente grandement son débit de larmes le temps d'une salle.",
    "Fait réapparaitre les monstres d'une salle.",
    "+0.7 Débit de larmes; +1 Coeur Bleu; Réduit considérablement la taille d'Isaac",
    "+1 Luck; Tant que vous possédez Mom's Box, l'effet de votre Trinket est doublé.",
    "+2 Hauteur de tir; -0.2 Vitesse de déplacement; -15 Portée d'attaque; Parfois, au lieu de tirer, Isaac va devenir tout rouge et charger énormément de larmes, en plus d'un caillot infligeant énormément de dégâts. ",
    "Isaac tire un laser similaire a celui utilisé par Mega Satan, pour 15 seconds. Le laser a assez de puissance pour pousser Isaac en arrière quand il est tiré. le laser reste activé entre les salles."
];

var Recharge = [
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "6",
    "3",
    "6",
    "1",
    "2",
    "1",
    "3",
    "Instantané",
    "3",
    "3",
    "2",
    "4",
    "X",
    "3",
    "X",
    "2",
    "X",
    "X",
    "X",
    "X",
    "X",
    "2",
    "X",
    "3",
    "X",
    "X",
    "X",
    "3",
    "2",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "6",
    "6",
    "X",
    "X",
    "X",
    "X",
    "X",
    "6",
    "6",
    "6",
    "3",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "6",
    "X",
    "X",
    "X",
    "4",
    "X",
    "X",
    "X",
    "X",
    "X",
    "6",
    "X",
    "X",
    "6",
    "X",
    "6",
    "X",
    "X",
    "X",
    "1",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "4",
    "4",
    "X",
    "Instantané",
    "Instantané",
    "X",
    "X",
    "6",
    "X",
    "X",
    "Instantané",
    "X",
    "Instantané",
    "3",
    "Instantané",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "1",
    "6",
    "3",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "6",
    "X",
    "4",
    "X",
    "X",
    "X",
    "4 secondes",
    "X",
    "6",
    "X",
    "X",
    "X",
    "X",
    "2",
    "X",
    "X",
    "X",
    "2",
    "X",
    "Instantané",
    "X",
    "X",
    "X",
    "6",
    "X",
    "X",
    "X",
    "X",
    "Instantané",
    "X",
    "X",
    "X",
    "X",
    "X",
    "2",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "Instantané",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "Instantané",
    "6",
    "6",
    "1",
    "4",
    "6",
    "2",
    "4 secondes",
    "Instantané",
    "6",
    "6",
    "6",
    "4 secondes",
    "Instantané",
    "Instantané",
    "Instantané",
    "4 secondes",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "6 tirs",
    "6",
    "2",
    "6, 1 par seconde",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "4 secondes",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    
    //========================//
    //       AFTERBIRTH       //
    //========================//
    
    "Instantané",
    "4",
    "X",
    "3",
    "3 secondes",
    "X",
    "X",
    "X",
    "X",
    "4",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "3",
    "1",
    "X",
    "X",
    "3",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "Instantané",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "4",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "4",
    "X",
    "2",
    "2",
    "X",
    "X",
    "X",
    "X",
    "1",
    "X",
    "X",
    "X",
    "X",
    "X",
    "X",
    "Instantané",
    "X",
    "X",
    "1",
    "X",
    "4",
    "X",
    "12",
];