var Name = [
    "Black Fly",
    "Attack Fly",
    "Ring Fly",
    "Moter",
    "Eternal Fly",
    "Pooter",
    "Fat Fly",
    "Boom Fly",
    "Red Boom Fly",
    "Level 2 Fly",
    "Full Fly",
    "Sucker",
    "Spit",
    "Dip",
    "Squirt",
    "Dinga",
    "Spider",
    "Big Spider",
    "Trite",
    "Ragling",
    "Level 2 Spider",
    "Ticking Spider",
    "Baby Long Legs",
    "Small Baby Long Legs",
    "Small Crazy Long Legs",
    "Crazy Long Legs",
    "Wall Creep",
    "Blind Creep",
    "Rage Creep",
    "Boil",
    "Gut",
    "Sack",
    "Walking Boil",
    "Walking Gut",
    "Walking Sack",
    "Round Worm",
    "Nightcrawler",
    "Mulligan",
    "Mulligoon",
    "Mulliboom",
    "Hive",
    "Nest",
    "Swarmer",
    "Hopper",
    "Flamming Hopper",
    "Leaper",
    "Pacer",
    "Gusher",
    "Gaper",
    "Frowning Gaper",
    "Gurgle",
    "Splasher",
    "Skinny",
    "Rotty",
    "Mr. Maw",
    "Horf",
    "Psychic Horf",
    "Maw",
    "Red Maw",
    "Psychic Maw",
    "Bony",
    "Death's Head",
    "One Tooth",
    "Lil' Haunt",
    "Wizoob",
    "Fatty",
    "Pale Fatty",
    "Fat Sack",
    "Blubber",
    "Half Sack",
    "Globin",
    "Gazing Globin",
    "Kinght",
    "Selfless Kinght",
    "Floating Knight",
    "Mask + Heart",
    "Clotty",
    "Clot",
    "I. Blob",
    "Mom's Hand",
    "Maggot",
    "Charger",
    "Spitty",
    "Conjoined Spitty",
    "Tumor",
    "Psy Tumor",
    "Camillo Jr.",
    "Brain",
    "MemBrain",
    "Guts",
    "Mama Guts",
    "ButtLicker",
    "Grub",
    "Para-Bite",
    "Codworm",
    "Fred",
    "Lump",
    "Leech",
    "Kamikaze Leech",
    "Holy Leech",
    "Host",
    "Red Host",
    "Walking Host",
    "Walking Red Host",
    "Nerve Ending",
    "Vis",
    "Double Vis",
    "Chubber",
    "Wall Hugger",
    "Slide",
    "Poky",
    "Eye",
    "Bloodshot Eye",
    "Dople",
    "Evil Twin",
    "Embryo",
    "Baby",
    "Angelic Baby",
    "Homunculus",
    "Begotten",
    "Null",
    "Swinger",
    "Keeper",
    "Hanger",
    "Stone Grimace",
    "Vomit Grimace",
    "Gaping Maw",
    "Turret Grimace",
    "Stone Eye",
    "Brimstone Eye",
    "Oob",
    "Blackmaw",
]

var description = [
    "Mouches noirs inoffensives vous suivant..",
    "Mouches rouges vous suivant et vous infligeant des dégâts au contact..",
    "Mouches violettes se rassemblant en anneau orbitant se lançant à votre poursuite.",
    "Vous suit de manière similaire aux autres mouches. Se divise en deux à sa mort.",
    "Mouche invulnérable tournant autour d’un caca. Ne peut être tuée qu’après destruction du caca.",
    "Mouche lente tirant une larme de sang dans votre direction. N’inflige pas de dégâts au contact.",
    "Version alternative des Pooter. Tire 2 larmes en V.",
    "Vole dans la salle en rebondissant sur les murs en diagonale, vous inflige des dégâts au contact et explosant à sa mort.",
    "Vole dans la salle en rebondissant sur les murs en diagonale, vous inflige des dégâts au contact et tire 6 larmes en étoiles à sa mort.",
    "Vole vers vous, traquant vos mouvements.",
    "Vole vers vous comme une Level 2 Fly. Tire 6 larmes en étoile à sa mort.",
    "Suit doucement votre personnage et explose en tirant 4 larmes dans les 4 directions.",
    "Avance doucement vers vous, tirant un projectile Ipecac dans votre direction à sa mort.",
    "Bouge aléatoirement dans la salle, vous inflige des dégâts au contact.",
    "Bouge dans la salle par à-coups de façon aléatoire, vous inflige des dégâts au contact. Se divise en 2 Dip à sa mort.",
    "Invoque périodiquement des Dips et tire dans les 6 directions. Se divise en 2 Squirts en mourant.",
    "Bouge de manière saccadée dans la salle, vous inflige des dégâts au contact.",
    "Bouge de manière saccadée dans la salle, se divise en deux à sa mort.",
    "Saute rapidement vers vous en parcourant de grandes distances.",
    "Saute rapidement vers vous en parcourant de grandes distances.",
    "Se balade aléatoirement dans la salle comme un spider. Peut sauter sur de courtes distances.",
    "Déambule dans la salle, vous infligeant des dégats et explose à sa mort. Peut sauter sur de courtes distances.",
    "S’éloigne rapidement de vous, et invoque des araignées fréquemment.",
    "S’éloigne rapidement de vous et invoque des sacks.",
    "S’approche de vous et tire dans les 8 directions.",
    "S’approche de vous et tire en X.",
    "S’aligne avec vous et tire 3 larmes à la suite dans votre direction.",
    "Déambule sur le mur, tirant 3 larmes en tir de dispersion.",
    "S’aligne avec vous et tire un tir Brimstone.",
    "Ennemi stationnaire, se réduisant en taille au fur et à mesure qu’il subit des dégâts. Il grossira rapidement s'il n’est pas tué à temps. Tire des larmes multiples à courtes portée dans une direction aléatoire une fois à sa taille maximale.",
    "Ennemi stationnaire, se réduisant en taille au fur et à mesure qu’il subit des dégâts. Il grossira rapidement s'il n’est pas tué à temps. Tire un Ipecac dans une direction aléatoire une fois à sa taille maximale.",
    "Ennemi stationnaire, se réduisant en taille au fur et à mesure qu’il subit des dégâts. Grossit plus lentement que Guts et Boils. Invoque des araignées une fois à sa taille maximale.",
    "Boil mobile ne pouvant réduire en taille, mais avec un nombre de point de vie fixe. Tire des larmes à courte portée de tailles variables avec une cadence de feu réduite.",
    "Gut mobile ne pouvant réduire en taille, mais avec un nombre de point de vie fixe. Tire un Ipecac avec une cadence de feu réduite.",
    "Sack mobile ne pouvant réduire en taille, mais avec un nombre de point de vie fixe. Invoque des araignées.",
    "Sort du sol et tire à vue sur vous.",
    "Tire des larmes orbitant en forme de +.",
    "Ennemi inoffensif déambulant dans la salle et vous évitant. Invoque plusieurs mouches à sa mort (noires ou rouges). Il peut également se suicider en tirant en X.",
    "Ennemi inoffensif déambulant dans la salle et vous évitant. Lâche une Troll BombTroll et tire en X à sa mort. Il peut également se suicider.",
    "Se déplace vers vous, explosant au contact ou à sa mort. L’explosion inflige un demi coeur de dégâts au lieu de 1 coeur entier.",
    "Déambule dans la salle, vous évitant et invoquant des Attack Flies. Invoque un grand nombre de Black Fly à sa mort. Ces mouches peuvent être des black flies, attack flies, ou Pooters/Fat Flies.",
    "Déambule dans la salle, vous évitant et invoquant des araignées. Invoque un Big Spider ou Trite en mourant.",
    "Flotte lentement dans la salle, invoquant un Pooter quand il subit des dégâts. Se transforme en Boom Fly à sa mort.",
    "Saute dans la salle doucement, vous infligeant des dégâts au contact. Peut se transformer en Flaming Hopper en touchant un feu.",
    "Saute dans la salle rapidement, parcourant de grandes distances.",
    "Saute dans la salle rapidement, mais pas aussi rapidement que les F. Hoppers. Peut parfois sauter haut dans le ciel pour retomber sur vous et tirer 4 larmes dans les 4 directions.",
    "Marche sans but dans la salle. Apparaît généralement après avoir tué un Gaper/Frowning Gaper.",
    "Marche sans but dans la salle, tirant des larmes à très courte portée depuis sa tête. Apparaît généralement après avoir tuer un Gaper/Frowning Gaper.",
    "Marche vers vous, vous inflige des dégâts au contact. Se transforme souvent en Pacer ou Gusher à sa mort.",
    "Marche vers vous, vous inflige des dégâts au contact. Une fois proche de vous, il ouvrira les yeux et gagnera en vitesse. Se transforme souvent enPacer.png ou Gusherpng à sa mort.",
    "Se déplace doucement vers vous, tirant un Ipecac. Il possède beaucoup plus de vie que les Gapers normaux. Peut se transformer en Splashers à sa mort.",
    "Déambule dans la salle, tirant des tirs Ipecac à courte portée.",
    "Marche lentement vers vous, laissant une traînée rouge derrière lui.",
    "Marche lentement vers vous, laissant une traînée rouge derrière lui. Peut se transformer en Bony ou en 2 mouches rouges à sa mort.",
    "Marche vers vous, lançant rapidement sa tête rattachée à son corps par un cordon. Se transforme en Maw ou en Pacer à sa mort selon la partie tuée.",
    "Ennemi stationnaire tirant des larmes à moyenne portée dans votre direction.",
    "Version alternative du Horf. Tirant des larmes téléguidées.",
    "Flotte lentement vers vous, tirant des larmes à grande vitesse.",
    "Flotte vers vous plus vite que les autres Maws, explosant en 4 larmes de sang dans les 4 directions à sa mort.",
    "Version alternative du Maw, a une mouche blanche tournant autour de lui. Tire de grosses larmes violettes téléguidées vers vous.",
    "Déambule dans la salle et tire un os si vous êtes devant lui et à portée.",
    "Ennemi invulnérable, bougeant en diagonale dans la salle, vous heurtant au contact. Il disparaît une fois tout les autres ennemis morts.",
    "Vous suit et vous fonce dessus périodiquement si vous êtes trop proche.",
    "Vous traque en tirant parfois des larmes. Il est capable de prédire vos mouvements, le rendant plus difficile à esquiver.",
    "Disparaît puis réapparaît près de vous en tirant des larmes spectrales.",
    "Marche lentement vers vous et pète occasionnellement, repoussant vous et les ennemis à distance.",
    "Crache 6 larmes en pétant. Il peut se transformer en headless fatty en mourant.",
    "Comme le Pale Fatty, mais peut en plus sauter sur vous et tirer 6 larmes en étoile en atterrissant.",
    "Déambule dans la salle et crache du sang. Peut se transformer en Half Sack à sa mort.",
    "Déambule dans la salle en laissant une traînée rouge derrière lui.",
    "Marche vers vous, infligeant un coeur de dégat au contact. Se transforme en pile de chair après avoir subit suffisamment de dégâts. Il se régénérera si vous lui laissez le temps au lieu de l’achever.",
    "Marche rapidement vers vous, infligeant un coeur de dégat au contact. Se transforme en pile de chair après avoir subit suffisamment de dégâts. Il se régénérera si vous lui laissez le temps au lieu de l’achever.",
    "Déambule dans la salle, vous prenant en chasse si vous êtes devant lui. Ne peut être touché que dans le dos",
    "Déambule dans la salle, vous prenant en chasse à grande vitesse si vous êtes devant lui. Ne peut être touché que dans le dos.",
    "Fonctionne comme un Knight mais à la capacité de voler.",
    "Masque invulnérable accompagné d’un coeur se déplaçant lentement. Le masque agit comme un Knight mais est invulnérable tandis que le coeur vous fuit. Le coeur tire dans les 4 directions si vous vous approchez. Tuer le coeur entraîne également la mort du masque",
    "Déambule dans la salle, tirant 4 larmes dans les 4 directions.",
    "Déambule dans la salle, tirant 4 larmes en X.",
    "Déambule dans la salle, tirant dans les 8 directions.",
    "Tombe depuis le plafond vers vous. Si elle vous tombe dessus, vous subissez un coeur de dégâts et vous êtes renvoyé dans la 1ère salle de l’étage. Vous pouvez prédire la position de ces mains en regardant la grande ombre grossissante autour de vous. Si vous entrez dans une salle contenant une Mom's Hand , le rire de mom vous préviendra de sa présence.",
    "Erre sans but dans la salle, vous heurtant au contact.",
    "Se déplace lentement dans la salle et vous charge si vous passez devant lui.",
    "Se déplace lentement dans la salle, tirant une larme à longue portée.",
    "Agit comme un Spitty but mais tire devant ET derrière lui.",
    "Se déplace en diagonale, tirant parfois 6 larmes. Tire plus souvent si il est blessé.",
    "Se déplace en diagonale, tirant parfois 6 larmes téléguidées. Tire plus souvent si il est blessé.",
    "Se déplace en diagonale, tirant un laser de type Technology vers vous. Tire plus souvent si il est blessé.",
    "Rampe dans la salle, laissant une traînée rouge sur son passage vous infligeant un coeur de dégât. Vous charge doucement après que vous soyez passé dans sa ligne de vue.",
    "Se déplace lentement dans la salle, rebondissant parfois sur place pour tirer 8 larmes dans toutes les directions. Se divise en 2 Brains en mourant.",
    "S’attache à un mur ou à un obstacle et le longe.",
    "Se déplace lentement dans la salle, rebondissant parfois sur place pour tirer 8 larmes dans toutes les directions. Se divise en 2 Guts à sa mort.",
    "S’attache aux autres Buttlickers, déambulant dans la salle de la même façon que Larry Jr.",
    "Bouge vers vous. Peut entrer sous terre pour en ressortir ailleurs.",
    "Se dépace frénétiquement dans la salle comme Larry Jr. et charge isaac quand il est dans la ligne de mire. Fait apparaître des vers de type aléatoire en mourant(1 par segment).",
    "Si vous lui tirez dessus, il repondra en tirant un petit barrage de tir. Il est invulnérable tant que sa tête n’est pas sortie.",
    "Tire un tir Ipecac vers vous. Il peut bondir du sol pour replonger sous terre afin de réapparaître ailleurs en tirant 4 larmes en X.",
    "Tire 3 larmes à grande vitesse vers vous une fois à portée avant de retourner sous terre afin d’en ressortir ailleurs.",
    "Vous prends en charge si vous êtes dans sa ligne de mire.",
    "Vous prends en charge si vous êtes dans sa ligne de mire et explose à sa mort.",
    "Vous prends en charge si vous êtes dans sa ligne de mire et explose à sa mort. Possède une Eternal Fly Eternal autour de lui.",
    "Ennemi stationnaire invulnérable. Il soulève sa tête quand vous êtes trop près, révélant son point faible. En levant sa tête , il tirera 3 larmes avant de la redescendre.",
    "Ennemi stationnaire. Il soulève sa tête quand vous êtes trop près. En levant sa tête , il tirera 5 larmes au lieu de 3 avant de la redescendre.",
    "Fonctionne comme the Host, mais se déplace dans la salle, infligeant des dégâts au contact.",
    "Fonctionne comme the Red Host, mais se déplace dans la salle, infligeant des dégâts au contact",
    "Ennemi statique bizarre agissant comme un bouclier humain.",
    "Charge un laser Brimstone quand vous passez devant lui.",
    "Charge un laser Brimstone devant ET derrière lui quand vous passez devant lui.",
    "Tire un Little Chubby infligeant un coeur de dégâts quand vous passez devant lui. Le Little Chubby bloque vos larmes.",
    "Se déplace dans la salle infligeant des dégâts au contact. Ne peut être détruit.",
    "Se déplace rapidement en ligne de droite vers vous quand vous passez dans sa ligne de mire, avant de revenir à sa position.",
    "Se déplace comme les Guts, vous heurtant au touché une fois leur pics sorti.",
    "Tourne doucement du regard vers vous et tire un laser si vous êtes trop lent ou immobile.",
    "Agit comme the Eye mais tire un brimstone à la place",
    "Copie vos mouvements, et tire en même temps que vous. Peut mourir en marchant sur des pics.",
    "Copie vos mouvements, tire en même temps que vous un triple tir similaire au Inner Eye et peut voler.",
    "Bondit sans but dans la salle, vous infligeant des dégâts au contact.",
    "Tire une seule larme. Peut se téléporter dans la salle.",
    "Tire 3 larmes en même temps, et possède bien plus de vie que les Babies.",
    "Il a une faible zone de déplacement car il est attaché à un mur. Il peut se détacher après un certain temps, tirant 6 larmes et vous prend en chasse.",
    "Agit comme les Homunculus. Quand il se libère du mur, il assombrit la lumière et devient temporairement invisible.",
    "Agit comme des Frowning Gapers. Quand vous êtes proches d’eux, ils deviennent invisibles périodiquement et se lancent à votre poursuite.",
    "Se déplace lentement vers vous avec une tête tournant autours de lui. Invoque un Maw ou un Globin selon la partie tuée en premier.",
    "Saute à travers la salle, tirant 2 larmes en V vers vous. Si vous êtes touché, vous perdrez 3 pièces et 2 tomberont par terre.",
    "Flotte dans la salle, tirant 3 larmes de sang vers vous. Possède une Eternal Fly15px autour de lui. Si vous êtes touché, vous perdrez 3 pièces et 2 tomberont par terre.",
    "Ennemi stationnaire et invulnérable tirant une larme de sang à grande vitesse. Devient inoffensif une fois la salle vidée de tout les autres ennemis.",
    "Ennemi stationnaire et invulnérable tirant un Ipecac. Devient inoffensif une fois la salle vidée de tout les autres ennemis.",
    "Ennemi stationnaire et invulnérable aspirant votre personnage vers lui.",
    "Ennemi stationnaire et invulnérable tirant des larmes non stop dans une certaine direction.",
    "Ennemi stationnaire et invulnérable tirant un laser technology en tournant sur lui même. Devient inoffensif une fois la salle vidée de tout les autres ennemis.",
    "Ennemi stationnaire et invulnérable tirant des brimstones non stop dans une certaine direction.",
    "Agit comme Famine. Quand votre personnage n’est pas horizontal avec lui, il invoque des Brains. Quand votre personnage est horizontal avec lui, il charge rapidement à travers la salle.",
    "Agit comme Famine. Quand votre personnage n’est pas horizontal avec lui, il invoque des Kamikaze Leeches. Quand votre personnage est horizontal avec lui, il charge très rapidement dans votre direction puis revient à sa position initiale. Il explose à sa mort.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
]