var Name = [
    "Swallowed Penny",
    "Petrified Poop",
    "AAA Battery",
    "Broken Remote",
    "Purple Heart",
    "Broken Magnet",
    "Rosary Bead",
    "Cartridge",
    "Pulse Worm",
    "Wiggle Worm",
    "Ring Worm",
    "Flat Worm",
    "Store Credit",
    "Callus",
    "Lucky Rock",
    "Mom's Toenail",
    "Black Lipstick",
    "Bible Tract",
    "Paper Clip",
    "Monkey Paw",
    "Mysterious Paper",
    "Daemon's Tail",
    "Missing Poster",
    "Butt Penny",
    "Mysterious Candy",
    "Hook Worm",
    "Whip Worm",
    "Broken Ankh",
    "Fish Head",
    "Pinky Eye",
    "Push Pin",
    "Liberty Cap",
    "Umbilical Cord",
    "Child's Heart",
    "Curved Horn",
    "Rusted Key",
    "Goat Hoof",
    "Mom's Pearl",
    "Cancer",
    "Red Patch",
    "Match Stick",
    "Lucky Toe",
    "Cursed Skull",
    "Safety Cap",
    "Ace of Spades",
    "Isaac's Fork",
    "Counterfeit Penny",
    "A Missing Page",
    "Bloody Penny",
    "Burnt Penny",
    "Flat Penny",
    "???'s Soul",
    "The Tick",
    "Isaac's Head",
    "Maggy's Faith",
    "Judas' Tongue",
    "The Left Hand",
    "Samson's Lock",
    "Cain's Eye",
    "Eve's Bird Foot",
    "Blister",
    "Black Feather",
    "Blasting Cap",
    "Blind Rage",
    "Cracked Dice",
    "Bob's Bladder",
    "Brown Cap",
    "Child Leash",
    "Faded Polaroid",
    "Endless Nameless",
    "Error",
    "Lazy Worm",
    "Golden Horse Shoe",
    "Karma",
    "Mom's Locket",
    "Lil Larva ",
    "Louse",
    "Poker Chip",
    "NO!",
    "Rib Of Greed",
    "Rainbow Worm",
    "Safety Scissors",
    "Shiny Rock",
    "Second Hand",
    "Stud Finder",
    "Store Key",
    "Super Magnet",
    "Tape Worm",
    "Watch Battery",
];

var Description = [
    "Fait apparaître une pièce à chaque fois que vous subissez des dégâts.",
    "Augmente grandement les chances de trouver des objets dans les cacas.",
    "Recharge automatiquement la dernière jauge d'un objet activable.",
    "A chaque fois qu'un objet activable est utilisé, téléporte Isaac dans une salle aléatoire.",
    "Donne une chance de transformer les Challenge Room en Boss Challenge Room. Augemente les chances de rencontrer des Champions ennemis.",
    "Attire les pièces vers Isaac. N'attire pas les autres objets.",
    "Augmente la Foi. Augmente les chances de faire apparaitre des Coeur blancs et d'obtenir une Angel Room après avoir vaincu le boss de l'étage",
    "Donne de faibles chances de se transformer en Pac Man invincible et mangeant ses adversaires lorsqu'Isaac subit des dégâts (même effet que le Gamekid).",
    "Les larmes d'Isaac varient constamment de taille. Les grosses larmes infligent plus de dégâts. Les petites larmes infligent moins de dégâts.",
    "Les larmes d'Isaac ont une trajectoire sinusoïdale.",
    "Les larmes d'Isaac ont une trajectoire en boucle.",
    "Les larmes d'Isaac sont plus larges et repoussent les ennemis.",
    "Le prochain achat dans le magasin est gratuit. Le trinket disparait après utilisation.",
    "Permet de marcher sur les piques et les flaques toxiques sans subir de dégâts.",
    "Les rochers et les champignons laissent des pièces lorsqu'ils sont explosés.",
    "Lorsque les secondes du chronomètre (touche Tab ou Select) atteignent 00, le pied de Maman tombe sur un personnage dans la salle. S'il n'y a plus d'ennemis, Isaac sera la cible.",
    "Diminue la Foi. Augmente les chances de trouver des Coeurs noirs et d'avoir une Devil Room à la fin de l'étage. Diminue les chances d'avoir des coeurs éternels et une Angel Room à la fin de l'étage.",
    "Augmente la Foi. Augmente les chances de faire apparaitre des Coeur blancs et d'obtenir une Angel Room après avoir vaincu le boss de l'étage.",
    "Permet d'ouvrir les coffres en or sans utiliser de clé.",
    "Fait apparaitre un Coeur noir au sol lorsqu'Isaac subit un dégât le mettant à moins d'un coeur rouge. Après trois Coeurs noirs, le trinket disparait.",
    "A une chance d'activer l'effet d'un autre Trinket lorsqu'Isaac subit des dégâts.",
    "Donne une énorme chance de faire apparaitre des Coeurs noirs plutôt que des Coeurs rouges.",
    "Si Isaac meurt dans la Sacrifice Room, une pièce de puzzle apparait dans le récapitulatif final. Cette pièce est un élément de l'énigme de The Lost.",
    "A chaque fois qu'une pièce est ramassée, Isaac lâche un pet qui repousse tous les ennemis proches.",
    "Isaac fait caca a des intervals de temps irréguliers.",
    "Les larmes d'Isaac ont une trajectoire semblable à une sinusoïde carrée.",
    "+1 Portée des tirs",
    "Lorsqu'il meurt en tenant cet objet, Isaac a une chance de revivre en tant que ???. Il est possible de renaitre plusieurs fois dans un même run, du moment que l'objet est tenu.",
    "Des mouches offensives apparaissent à chaque fois qu'Isaac subit des dégâts.",
    "Donne 10% de chance de tirer une larme empoisonnée.",
    "Donne 10% de chance de tirer une larme traversant les obstacles.",
    "A chaque fois qu'il change de salle, Isaac gagne temporairement l'effet d'un des objets champignons du jeu. Peut également révéler temporairement l'emplacement des salles spéciales d'un étage.",
    "Lorsqu'Isaac n'a plus qu'un demi-coeur, un Little Steven aux larmes à tête chercheuse apparait.",
    "Augmente les chances de trouver des coeurs dans les coffres ou après avoir terminé une salle.",
    "+2 Dégâts",
    "Augmente les chances de faire apparaitre des clés et des Coffres en or en terminant une salle.",
    "+0.15 Vitesse de déplacement.",
    "Donne 10% de chance de faire apparaitre des Coeurs bleus plutôt que des Coeurs rouges.",
    "+2 Cadence de tir",
    "Donne 20% de chance de faire plus de dégâts lorsqu'Isaac subit des dégâts. (Similaire à l'objet Razor Blade.)",
    "Augmente les chances de faire apparaitre des bombes dans les coffres ou en terminant une salle.",
    "Augmente les chances d'avoir un objet en terminant une salle. N'augmente pas la statistique Chance d'Isaac.",
    "Si Isaac subit des dégâts qui devraient le laisser à moins d'un coeur rouge entier, il est téléporté dans la dernière salle qu'il a terminé.",
    "Augemente les chances de trouver une pillule dans les coffres et en terminant une salle.",
    "Augmente les chances de trouver des cartes de tarot ou de jeux dans les coffres ou après avoir terminé une salle.",
    "Isaac a 10% de chance de récupérer un demi-coeur lorsqu'il termine une salle.",
     "Les pièces ont 50% de chance de voir leur valeur doubler lorsqu'elles sont ramassées.",
    "Lorsqu'Isaac se fait toucher, il a 5% de chance d'utiliser le Necronomicon et d'infliger des dégâts à tous les ennemis de la salle.",
    "A chaque fois qu'une pièce est ramassée, a 50% de chance de faire apparaitre un demi coeur rouge au sol.",
    "A chaque fois qu'une pièce est ramassée, a 50% de chance de faire apparaitre une bombe au sol.",
    "A chaque fois qu'une pièce est ramassée, a 50% de chance de faire apparaitre une clé au sol.",
    "Fait apparaitre un familier qui flotte dans la salle et tire des larmes spectrales à têtes chercheuses. Les autres familliers suivront ???'s Soul plutôt qu'Isaac.",
    "Les boss perdent immédiatement 15% de leurs vies en début de combat. Rend un Coeur rouge à Isaac lorsqu'il rentre dans la salle du Boss pour la première fois. La Tique ne peut plus être retirée une fois prise.",
    "Donne un famillier qui suit Isaac et tire des larmes transperçant les ennemis.",
    "Donne un Coeur blanc au début de chaque étage.",
    "Les objets des Devil Room coutant 2 Coeurs rouges n'en coutent plus qu'un seul. Ne change rien aux objets coutant 3 Coeurs bleus.",
    "Remplace les coffres et les coffres dorés par des coffres rouges.",
    "Donne une chance sur quinze d'augmenter les dégâts d'Isaac de 0.5 le temps d'une salle à chaque ennemis tués.",
    "Au début de chaque étage, donne une chance sur quatre de voir où se trouve les salles spéciales (dans un effet similaire à The Compass).",
    "Lorsqu'Isaac tue un ennemi, il a 5% de chance de faire apparaitre un Dead Bird attaquant les ennemis le temps d'une salle.",
    "Les larmes d'Isaac repousse les ennemis plus loin.",
    "Les dégâts d'Isaac sont augmentés quand il possède des objets du démon.",
    "Lorsqu'une bombe explose il y a une chance qu'une autre bombe apparaisse.",
    "Augmente la durée d'invincibilité après avoir été touché.",
    "Quand Isaac se fait toucher il y a une chance que l'effet du D6, D8, D12 ou D20 s'active.",
    "Libère une flaque verte quand les bombes explosent qui font des dégâts aux ennemies.",
    "Les cacas explosent quand ils sont détruits.",
    "Les familiers sont plus proche les uns des autres.",
    "Parfois Isaac se fond dans le décor, les ennemies deviennent alors confus.",
    "Quand Isaac utilise une carte, une pillule ou une rune, il y a une chance qu'il y ait un objet du même type apparaisse.",
    "Donne l'effet d'un trinket aléatoire chaque salle.",
    "La vitesse des larmes est très ralentie.",
    "15% que la salle au trésor contienne deux objets au lieu de deux.",
    "Faire des dons à la machine de dons a une chance de soigner Isaac ou de faire apparaître un mendiant. Augmente la chance que quand Isaac donne des pièces à la machine de dons sa chance augmente.",
    "Soigne Isaac à chaque fois qu'une clé est utilisée. Convertit les demis coeurs rouges en un coeur entier.",
    "Fait appraître une mouche à chaque fois qu'un caca est détruit.",
    "Faît apparaître parfois des arraignées bleues.",
    "Les coffres ont 50% de chance de donner des consommables en plus ou 50% chance de donner soit rien ou soit des ennemies.",
    "Enlève les objets activables de liste des objets.",
    "Greed et Super Greed ne peuvent ni appraître dans le magasin ni dans les salles secrètes.",
    "Les larmes d'Isaac prennent l'effet d'un des trinkets 'Worm' toutes les 3 secondes.",
    "Les Troll Bombes se transforment en bombes consommables avant qu'elles n'explosent. Les Mega Troll Bombes se transforment en 2 bombes consommables.",
    "Les rochers marqués d'une croix brillent.",
    "Augmente le temps de pétrification des ennemies.",
    "Augmente la chance de trouver des échelles de corde.",
    "Ouvre les portes du magasin automatiquement.",
    "Repousse les objets et les consommables.",
    "Double la portée des larmes d'Isaac et réduit de moitié la hauteur de celles-ci.",
    "Augmente la chance de faire apparaître des piles.",
];